apiVersion: v1
data:
  jupyterhub_config.py: IyB1c2UgZ2l0aHViIGF1dGhlbnRpY2F0b3IKZnJvbSBvYXV0aGVudGljYXRvci5naXRodWIgaW1wb3J0IEdpdEh1Yk9BdXRoZW50aWNhdG9yCmMuSnVweXRlckh1Yi5hdXRoZW50aWNhdG9yX2NsYXNzID0gR2l0SHViT0F1dGhlbnRpY2F0b3IKCiMgc3BlY2lmeSB1c2VycyBhbmQgYWRtaW4KYy5BdXRoZW50aWNhdG9yLndoaXRlbGlzdCA9IHsnZGVyZWtwZWRlcnNlbid9CmMuQXV0aGVudGljYXRvci5hZG1pbl91c2VycyA9IHsnZGVyZWtwZWRlcnNlbid9Cg==
  oauth_client_id: 
  oauth_client_secret: 
kind: Secret
metadata:
  name: jupyterhub-config
  namespace: default
type: Opaque
